app = "your-app-name" # change this to something unique, like bbl-shell

primary_region = "iad"

[build]
  image = "ghcr.io/kelodontplay/fly-shell:latest"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
